namespace: dev
replicaCount: 1

image:
  repository: europe-central2-docker.pkg.dev/golang-blueprint/golang-blueprint-basic/api
  pullPolicy: IfNotPresent
  tag: latest

service:
  ports:
    http:
      port: 80
      protocol: TCP

app:
  env: dev
  ports:
    http:
      port: 8080
      protocol: TCP
  logLevel: debug
  dbConnStr: ""
  dbMigrate: true


