apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    helm.sh/chart: {{ .Chart.Name }}
  ports:
    - name: https
      port: {{ .Values.service.ports.https.port }}
      protocol: {{ .Values.service.ports.https.protocol }}
      targetPort: {{ .Values.app.ports.http.port }}
    - name: http
      port: {{ .Values.service.ports.http.port }}
      protocol: {{ .Values.service.ports.http.protocol }}
      targetPort: {{ .Values.app.ports.http.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      helm.sh/chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.ports.http.port }}
              protocol: {{ .Values.app.ports.http.protocol }}
          args:
            - "serve"
            - "-http-addr=:{{ .Values.app.ports.http.port }}"
            - "-db-conn-str={{.Values.app.dbConnStr }}"
            - "-db-migrate={{ .Values.app.dbMigrate}}"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: {{ .Values.app.ports.http.port }}
              path: "/health"
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: {{ .Values.app.ports.http.port }}
              path: "/health"