apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.service.subdomain }}.{{ .Values.service.domain }}"
    kubernetes.digitalocean.com/load-balancer-id: {{ .Chart.Name }}
    service.beta.kubernetes.io/do-loadbalancer-name: "{{ .Values.service.domain }}"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "{{ .Values.service.loadBalancer.size }}"
    service.beta.kubernetes.io/do-loadbalancer-protocol: {{ .Values.service.loadBalancer.protocol }}
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.service.loadBalancer.certID }}
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "true"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "10"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
  labels:
    helm.sh/chart: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    helm.sh/chart: {{ .Chart.Name }}
  ports:
    - name: https
      port: {{ .Values.service.ports.https.port }}
      protocol: {{ .Values.service.ports.https.protocol }}
      targetPort: {{ .Values.app.ports.http.port }}
    - name: http
      port: {{ .Values.service.ports.http.port }}
      protocol: {{ .Values.service.ports.http.protocol }}
      targetPort: {{ .Values.app.ports.http.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      helm.sh/chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.ports.http.port }}
              protocol: {{ .Values.app.ports.http.protocol }}
          args:
            - "serve"
            - "-loglvl={{ .Values.app.logLevel }}"
            - "-httpaddr=:{{ .Values.app.ports.http.port }}"
            - "-dbconnstr={{.Values.app.dbConnStr }}"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: {{ .Values.app.ports.http.port }}
              path: "/health"
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: {{ .Values.app.ports.http.port }}
              path: "/health"