name: Basic Deploy

on:
  push:
    paths:
      - '.github/workflows/basic-deploy.yml'
      - 'basic/**'
    branches:
      - main

defaults:
  run:
    working-directory: basic

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: basic
          version: latest
          args: --timeout=3m

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_JSON_KEY }}

      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker europe-central2-docker.pkg.dev

