name: API Deploy

on:
  push:
    paths:
      - '.github/workflows/basic-deploy.yml'
      - 'basic/**'
    branches:
      - main

defaults:
  run:
    working-directory: basic

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m