name: Basic Deploy

on:
  push:
    tags:
      - "v1.*"
    paths:
      - '.github/workflows/basic-deploy-stage.yml'
      - 'basic/**'
    branches:
      - main

defaults:
  run:
    working-directory: basic

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: basic
          version: latest
          args: --timeout=3m

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_JSON_KEY }}

      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Docker build
        run: |
          docker build \
          --build-arg BRANCH=${{ github.ref }} \
          --build-arg COMMIT=${{ github.sha }} \
          -t europe-central2-docker.pkg.dev/golang-blueprint/golang-blueprint-basic/api:${{ github.sha }} \
          -t europe-central2-docker.pkg.dev/golang-blueprint/golang-blueprint-basic/api:latest \
          .

      - name: Docker push
        run: |
          docker push europe-central2-docker.pkg.dev/golang-blueprint/golang-blueprint-basic/api:${{ github.sha }}
          docker push europe-central2-docker.pkg.dev/golang-blueprint/golang-blueprint-basic/api:latest

